
[package]
name = "smoothie-rs"
version = "0.1.0"
edition = "2021"

[dependencies]

clap = {version = "4.0.14", features = ["derive"] }
color-eyre = "0.6.2"

human-panic = "1.0.3"


serde = "1.0.152"
serde_derive = "1.0.152"
serde_json = "1.0.91"
