
[package]
name = "smoothie-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {version = "4.0.14", features = ["derive"] } # cli helper
color-eyre = "0.6.2" # error handling

# json stuff
serde = "1.0.152" 
serde_derive = "1.0.152"
serde_json = "1.0.91"

# win32
[dependencies.windows]
version = "0.43.0"
features = [
    "Win32_UI_HiDpi", 
    "Win32_System_Console", 
    "Win32_Foundation", 
    "Win32_UI_WindowsAndMessaging",
    "Win32_Graphics_Gdi",
    "Win32_UI_Controls_Dialogs"
    ]
