
[package]
name = "smoothie-rs"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
clap = {version = "4.1.4 ", features = ["derive"] } # cli arg helper
color-eyre = "0.6.2" # error handling
ffprobe = "0.3.3"
open-file = "0.1.0"  # open file with default app
rand = "0.8.5"  # randomly choose from fruits for suffix
rfd = "0.11.0"  # open file dialog
which = "4.4.0" # Get-Command / where.exe / which alternative
# rustsynth = "0.2.1" # wrapper for VapourSynth.dll
# rustsynth = {path = "./rustsynth/rustsynth/"}

# json stuff
serde = "1.0.152" 
serde_derive = "1.0.152"
serde_json = "1.0.91"
reqwest = {version = "0.11.14", features = ["json"]}
tokio = { version = "1.25.0", features = ["full"]}
colored = "2.0.0"
enable-ansi-support = "0.2.1"

[build-dependencies]
winres = "0.1" # give the exe an icon

# win32, mainly used for to move the tui console to a corner
[dependencies.windows]
version = "0.43.0"
features = [
    "Win32_UI_HiDpi", 
    "Win32_System_Console", 
    "Win32_Foundation", 
    "Win32_UI_WindowsAndMessaging",
    "Win32_Graphics_Gdi",
    "Win32_UI_Controls_Dialogs"
    ]

# for myself, uncommenting when building for release

# [profile.release]
# strip = true
# opt-level = "s"
# lto = true
# codegen-units = 1
