name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-2019]
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: true
        install: mingw-w64-clang-x86_64-clang
    - name: Set LIBCLANG_PATH
      run: echo "LIBCLANG_PATH=$((gcm clang).source -replace "clang.exe")" >> $env:GITHUB_ENV
    - name: Ship
      shell: pwsh
      run: |
        curl -s -o mingw.7z -L https://github.com/brechtsanders/winlibs_mingw/releases/download/12.2.0-15.0.7-10.0.0-msvcrt-r4/winlibs-x86_64-posix-seh-gcc-12.2.0-llvm-15.0.7-mingw-w64msvcrt-10.0.0-r4.7z
        7z x .\vs.7z -omingdw
        $env:LIBCLANG_PATH=(Get-Item ./mingw/mingw64/bin/).FullName
        curl -s -o vs.7z -L https://github.com/AmusementClub/vapoursynth-classic/releases/download/R57.A8/release-x64.zip
        7z x .\vs.7z -ovapoursynth
        $env:VAPOURSYNTH_LIB_DIR=(Get-Item ./vapoursynth/sdk/lib64/).FullName

        mkdir ./smoothie-rs-artifact/bin/
        cargo build --release
        mv ./target/release/smoothie-rs.exe ./smoothie-rs-artifact/bin/
        mv ./target/*.ini ./smoothie-rs-artifact/

        
        'msvcp140.dll','vcruntime140_1.dll', 'vcruntime140.dll','VapourSynth.dll' | ForEach-Object {
          7z e vs.7z -osmoothie-rs-artifact/bin/ $PSItem
        }
        

        set-content ./smoothie-rs-artifact/launch.cmd -value '@echo off & cd /D "%~dp0" & .\bin\smoothie-rs.exe --tui & pause'
        7z a -t7z -mx=5 artifact.zip ./smoothie-rs-artifact/
    - uses: actions/upload-artifact@v3
      with:
        name: smoothie-rs-bin-windows
        path: artifact.zip
